services:
  app:
    build: ./fastapi
    env_file:
       - ./fastapi/.env
    container_name: my-fastapi-server
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    environment:
      TZ: Asia/Seoul

volumes:
  ky_db_data_v3: